#!/usr/bin/env bash

set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../lib/common.sh
source "$ROOT_DIR/lib/common.sh"

parse_config_only_args "$@" || true
load_config

cat <<DNS
Publish these DNS records:

DNS

while IFS= read -r domain; do
  cat <<DNS
$domain. MX 10 $MAIL_HOSTNAME.
DNS
done < <(mail_domains)

declare -A printed_hosts=()
print_host_record() {
  local host="$1"
  local type="$2"
  local value="$3"
  local key="$host|$type|$value"
  [[ -n "$host" ]] || return 0
  [[ -z "${printed_hosts[$key]:-}" ]] || return 0
  printed_hosts[$key]=1
  printf '%s. %s %s\n' "$host" "$type" "$value"
}

print_host_record "$MAIL_HOSTNAME" A "$SERVER_PUBLIC_IPV4"
print_host_record "$WEBMAIL_HOSTNAME" A "$SERVER_PUBLIC_IPV4"
print_host_record "$DAV_HOSTNAME" A "$SERVER_PUBLIC_IPV4"

while IFS= read -r domain; do
  cat <<DNS
$domain. TXT "v=spf1 mx -all"
_dmarc.$domain. TXT "v=DMARC1; p=none; rua=mailto:dmarc@$domain; adkim=s; aspf=s"
DNS
done < <(mail_domains)

if [[ -n "${SERVER_PUBLIC_IPV6:-}" ]]; then
  print_host_record "$MAIL_HOSTNAME" AAAA "$SERVER_PUBLIC_IPV6"
  print_host_record "$WEBMAIL_HOSTNAME" AAAA "$SERVER_PUBLIC_IPV6"
  print_host_record "$DAV_HOSTNAME" AAAA "$SERVER_PUBLIC_IPV6"
fi

while IFS= read -r domain; do
  dkim_txt="$DKIM_ROOT/$domain/$DKIM_SELECTOR.txt"
  if [[ -f "$dkim_txt" ]]; then
    printf '\nDKIM record generated by OpenDKIM for %s:\n\n' "$domain"
    sed 's/[[:space:]]\+/ /g' "$dkim_txt"
  else
    cat <<DNS

DKIM record for $domain is not generated yet. Run install phase 70 or the full installer, then rerun this command.
Expected name: $DKIM_SELECTOR._domainkey.$domain.
DNS
  fi
done < <(mail_domains)

cat <<DNS

Provider PTR/rDNS must be:
$SERVER_PUBLIC_IPV4 -> $MAIL_HOSTNAME
DNS

if [[ -n "${SERVER_PUBLIC_IPV6:-}" ]]; then
  cat <<DNS
$SERVER_PUBLIC_IPV6 -> $MAIL_HOSTNAME
DNS
fi
